### ISSUE TITLE
Getting an error when using '--keywords' option in bulk 

### ISSUE THREAD

**Issue by iamyihwa** [koaning/bulk#36]
Hello @koaning  thanks for such a great library! 

I am getting an error when I am using '--keywords' option in the bulk. 
It works great, if I don't use '--keywords' option .. 
I wonder what the cause is .. 

> python -m bulk text ready2.csv --keywords "frozen"

About to serve `bulk` over at http://localhost:5006/.
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\tornado\web.py", line 1713, in _execute
    result = await result
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\views\session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\application\application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\application\handlers\function.py", line 143, in modify_document
    self._func(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bulk\text.py", line 27, in bkapp
    mapper, df = get_color_mapping(df)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bulk\utils.py", line 25, in get_color_mapping
    palette=Category10[len(all_values)],
KeyError: 1
500 GET / (::1) 28.95ms

**Comment by koaning** [comment]
I think I know whats going wrong there. Try "frozen,foobar" for now.

**Comment by iamyihwa** [comment]
Hi @koaning  Thanks for your quick reply. 
However same error with two keywords as well.. .. 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/12494156/201337079-7ebf760f-f0af-4dcf-ad9d-b0c5dd34f3ec.png">

**Comment by koaning** [comment]
Please share errors using the markdown blocks. Screenshots are horrible to copy/paste from and they also don't show up in search results. 

Will have a look tho! Thanks for reporting.

**Comment by iamyihwa** [comment]
Sure! Sorry for that! 

```
(SemanticMatching) PS C:\Users\kiyi2001\Documents\Projects\SemanticMatching> python -m bulk text ready2.csv --keywords "frozen,foobar"
About to serve `bulk` over at http://localhost:5006/.
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\tornado\web.py", line 1713, in _execute
    result = await result
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\views\session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\application\application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\application\handlers\function.py", line 143, in modify_document
    self._func(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bulk\text.py", line 27, in bkapp
    mapper, df = get_color_mapping(df)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bulk\utils.py", line 25, in get_color_mapping
    palette=Category10[len(all_values)],
KeyError: 1
500 GET / (::1) 22.97ms
```

**Comment by koaning** [comment]
Just to double check ... what version of bulk are you running?

**Comment by iamyihwa** [comment]
Version 0.0.4 

I just installed it with .. 
>  pip install bulk 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/12494156/201384756-14e4e006-5ad7-49d8-8f53-bd73fc7f268b.png">

**Comment by koaning** [comment]
https://pypi.org/project/bulk/#history

The most recent version is v0.1.3, could you install that manually and try again? 

```
python -m pip install --upgrade bulk
```

**Comment by koaning** [comment]
Also, what version of Python are you running?

**Comment by iamyihwa** [comment]
Python 3.7.2

**Comment by iamyihwa** [comment]
Just upgraded .. However getting the same error ... 

```
>python -m pip install --upgrade bulk
...
Successfully uninstalled bulk-0.0.4
Successfully installed bulk-0.1.3
(SemanticMatching) PS C:\Users\kiyi2001\Documents\Projects\SemanticMatching> python -m bulk text ready2.csv --keywords "frozen,refrigerated"
About to serve `bulk` over at http://localhost:5006/.
Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\tornado\web.py", line 1713, in _execute
    result = await result
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\views\session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\server\contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\application\application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bokeh\application\handlers\function.py", line 143, in modify_document
    self._func(doc)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bulk\cli\text.py", line 34, in bkapp
    mapper, df = get_color_mapping(df)
  File "C:\Users\kiyi2001\Miniconda3\envs\SemanticMatching\lib\site-packages\bulk\_bokeh_utils.py", line 32, in get_color_mapping
    palette=Category10[len(all_values)],
KeyError: 1
```

**Comment by koaning** [comment]
I just had a look at this error again but had trouble reproducing it. But I did confirm that the Bokeh coloring util only accepts situations with at least 3 colors. 

Is it possible to share a minimum viable subset of the data that might allow me to reproduce this issue locally?

**Comment by iamyihwa** [comment]
Thanks @koaning  for checking back the issue! 
I have tried again, and it seems this time to work all fine! 
I will close the issue.
